### ISSUE TITLE
Peer-Dependecy on node-cache

### ISSUE THREAD

**Issue by dasniko** [raulanatol/axios-etag-cache#11]
Hi,

as I already wrote in one of my PRs, I really like your package!

You have a peer dependency on `node-cache` but don't have an option to configure the cache object when creating. This default behaviour of node-cache is similar to use just a static singleton object and adds a massive amount of code to ones project, w/o delivering value.

So, I would recommend to either skip the `node-cache` dependency and to use a plain object, or to allow for an optional `options` object when creating the cache object.

WDYT?

**Comment by raulanatol** [comment]
Hi @dasniko this is a good recommendation.

I'm working on it in this branch: [node_cache_remove_dependencies](https://github.com/raulanatol/axios-etag-cache/tree/node_cache_remove_dependencies)

Thanks a lot.

**Comment by dasniko** [comment]
Had just a quick view into it, looks nice.
So, one can just use the cache provider one wants, as long as it supports the interface, right?

**Comment by raulanatol** [comment]
Exactly, if you have any choice I can prove it.

**Comment by Yankovsky** [comment]
Let's just make node-cache a dependency instead of peer dependency.
