### ISSUE TITLE
Sub Package Vulnerability - axios@0.21.4

### ISSUE THREAD

**Issue by WilliamHolmes** [raulanatol/axios-etag-cache#29]
The dependency axios@0.21.4 contains a vulnerability and needs to be updated.

https://snyk.io/vuln/npm:axios

### Release Notes

<details>
<summary>axios/axios</summary>

### [`v0.24.0`](https://github.com/axios/axios/blob/master/CHANGELOG.md#&#8203;0240-October-25-2021)

[Compare Source](https://github.com/axios/axios/compare/v0.23.0...v0.24.0)

**Comment by raulanatol** [comment]
@WilliamHolmes thanks for your notice.

I will finish a new release ASAP.
