### ISSUE TITLE
Unable to getCacheByAxiosConfig - infinite recursion

### ISSUE THREAD

**Issue by cwadding** [raulanatol/axios-etag-cache#37]
On lines:
https://github.com/raulanatol/axios-etag-cache/blob/main/src/index.ts#L16-L21
the function getCacheByAxiosConfig is recursively calling itself and never returns the value from the cache.

This should be updated to the following:
```js
function getCacheByAxiosConfig(config) {
  const url = getUUIDByAxiosConfig(config);
  if (url) {
    return Cache.get(url);
  }
  return null;
}
```

to use the same value that is used to set the item in the cache

**Comment by raulanatol** [comment]
@cwadding, thanks for your notice.

I've fixed the error on #38 and I will publish a new version ASAP.
