### ISSUE TITLE
Conflict with xsrfCookieName and xsrfHeaderName options

### ISSUE THREAD

**Issue by p1Machado** [raulanatol/axios-etag-cache#5]
With axios-etag-cache enabled, post requests don't send the CSRF header.

**Comment by raulanatol** [comment]
Sorry @p1Machado 🤦‍♂ 
Please can you put an example?

**Comment by p1Machado** [comment]
> Sorry @p1Machado 🤦‍♂
> Please can you put an example?

**Comment by p1Machado** [comment]
Accidentally clicked close.

Let me try to reproduce it.

**Comment by p1Machado** [comment]
Sorry man, I couldn't reproduce it in a codesandbox because of cors policy. Actually I solved my problem using another lib:
```javascript
import axios from 'axios';
import { cacheAdapterEnhancer } from 'axios-extensions';

export const instance = axios.create({
  xsrfCookieName: '_csrf_token',
  xsrfHeaderName: 'X-CSRF-Token',
  adapter: cacheAdapterEnhancer(axios.defaults.adapter, { enabledByDefault: false })
});
```
