### ISSUE TITLE
IE 11 problem

### ISSUE THREAD

**Issue by KosKosovuch** [raulanatol/axios-etag-cache#7]
Don't work on IE11

**Comment by raulanatol** [comment]
Sorry @KosKosovuch 🤦‍♂️
Please can you put an example or more information?
Thanks!

**Comment by KosKosovuch** [comment]
You have in your build code you have class Cache and you need to build it with babel to compile to ES5.
`class o {
        static getInstance() {
            return this.instance || (this.instance = new o), this.instance
        }
        static get(e) {
            return this.getInstance().cache.get(e)
        }
        static set(e, t, n) {
            return this.getInstance().cache.set(e, {
                etag: t,
                value: n
            })
        }
        static reset() {
            this.getInstance().cache.flushAll()
        }
        constructor() {
            this.cache = new r
        }
    }
    t.Cache = o
}`
